In [1]:
# Code to remove 'Misc' label from segmentation files only [FUNCTIONAL]

import nrrd
import numpy as np

def remove_label(nrrd_file, label_to_remove, output_file):
    # Load the NRRD file
    data, header = nrrd.read(nrrd_file)

    # Identify the label value to remove
    labels = np.unique(data)
    if label_to_remove not in labels:
        print(f"Label {label_to_remove} not found in the segmentation.")
        return

    # Remove the specified label
    data[data == label_to_remove] = 0


    # Save the modified data to a new NRRD file
    nrrd.write(output_file, data, header)

# Replace these paths and label value with your actual data
input_nrrd_file = 'C:/Users/Adam/Desktop/Programs/code_testing/python_file_rename_copy/Case-22-0.5_A_80KV_Qr40d_3_53062428/MarkUps/88-Jensen/S-Segmentation-1.nrrd'
output_nrrd_file = 'C:/Users/Adam/Desktop/Programs/code_testing/python_file_rename_copy/Case-22-0.5_A_80KV_Qr40d_3_53062428/MarkUps/88-Jensen/S-Segmentation-1-AV2.nrrd'
label_to_remove = 3

A = 


# Call the function to remove the label
remove_label(input_nrrd_file, label_to_remove, output_nrrd_file)

KeyboardInterrupt: 

In [6]:
# [FUNCTIONAL] Takes .nrrd file, saves as new file that only retains segmentations with the value of 0, 1, 2

import nrrd
import numpy as np

file_path = 'C:/Users/Adam/Desktop/Programs/code_testing/python_file_rename_copy/Case-22-0.5_A_80KV_Qr40d_3_53062428/MarkUps/88-Jensen/S-Segmentation-1.nrrd'
output_file_path = 'C:/Users/Adam/Desktop/Programs/code_testing/python_file_rename_copy/Case-22-0.5_A_80KV_Qr40d_3_53062428/MarkUps/88-Jensen/S-Segmentation-1-newTest1.nrrd'

data, header = nrrd.read(file_path)
valid_segmentation_values = [0, 1, 2]

# Calculate voxel counts for each segmentation value
voxel_counts = {}
for value in valid_segmentation_values:
    voxel_counts[str(value)] = np.count_nonzero(data == value)

# Sort the voxel counts from most to least
sorted_voxel_counts = sorted(voxel_counts.items(), key=lambda x: x[1], reverse=True)

# Print and store the counts for each value
for value, count in sorted_voxel_counts:
    print(f"Segmentation value {value} has {count} voxels.")
    
    # You can also store the counts in separate variables if needed
    if value == '0':
        count_value_0 = count
    elif value == '1':
        count_value_1 = count
    elif value == '2':
        count_value_2 = count
    elif value == '3':
        count_value_3 = count

print(count_value_0)
print(count_value_1)
print(count_value_2)
print(count_value_3)

# Replaces values not in 'valid_segmentation_values' with 0
data[np.logical_not(np.isin(data, valid_segmentation_values))] = 0

# Save the modified data as a new .nrrd file

nrrd.write(output_file_path, data, header)








Segmentation value 0 has 24126732 voxels.
Segmentation value 1 has 2409746 voxels.
Segmentation value 2 has 1882369 voxels.
24126732
2409746
1882369


NameError: name 'count_value_3' is not defined

In [2]:
# [FUNCTIONAL] Gets the 4 main segmentation labels (0, 1, 2, 3), sets all '3' voxels to 0, reports the counts of all 4 segmentation labels

import numpy as np
import nrrd

# File paths
file_path = 'C:/Users/Adam/Desktop/Programs/code_testing/python_file_rename_copy/Case-22-0.5_A_80KV_Qr40d_3_53062428/MarkUps/88-Jensen/S-Segmentation-1.nrrd'
output_file_path = 'C:/Users/Adam/Desktop/Programs/code_testing/python_file_rename_copy/Case-22-0.5_A_80KV_Qr40d_3_53062428/MarkUps/88-Jensen/S-Segmentation-1-newTest3.nrrd'

# Store file info
data, header = nrrd.read(file_path)

# Defines the valid segmentation values (0, 1, 2, 3)
valid_segmentation_values_all = [0, 1, 2, 3]

# Segmentation values that will be retained in output file
valid_segmentation_values_kept = [0, 1, 2]

# Calculates voxel counts for each segmentation value
unique_values, counts = np.unique(data, return_counts=True)

# Creates a dictionary to store counts based on segment label name
segment_counts = {}
for value, count in zip(unique_values, counts):
    segment_counts[str(value)] = count

# Replaces values not in valid_segmentation_values with 0
data[np.logical_not(np.isin(data, valid_segmentation_values_kept))] = 0

# Print or access the counts
print("Segment Counts:", segment_counts)

nrrd.write(output_file_path, data, header)


[0 1 2 3]
[0 1 2 3]
[0 1 2 3]
[0 1 2 3]
Segment Counts: {'0': 24126732, '1': 2409746, '2': 1882369, '3': 201476973}


In [3]:
# (WIP)

import numpy as np
import nrrd

# Load the .nrrd file
file_path = 'C:/Users/Adam/Desktop/Programs/code_testing/python_file_rename_copy/Case-22-0.5_A_80KV_Qr40d_3_53062428/MarkUps/88-Jensen/S-Segmentation-1.nrrd'
data, header = nrrd.read(file_path)

# Get the unique segment label values
unique_segment_labels = np.unique(data)

print(header)

# # Convert segment labels to string and store in a variable
# segment_label_names = [str(label) for label in unique_segment_labels]

# # Print the segment label names
# print("Segment Label Names:", segment_label_names)



print(header)

# # Get the segment label names from the header metadata
# segment_label_names = header.get('SegmentLabelNames', [])

# # Print the segment label names
# print("Segment Label Names:", segment_label_names)

# # Get the segment label information from the header
# segment_mapping = header.get('segment', {})

# # Print the segment label information
# print("Segment Label Information:", segment_mapping)


# # Get the unique segment label values
# unique_segment_labels = np.unique(data)

# # Get the mapping of segment label numbers to names from the header
# segment_mapping = header['segment']

# Create a dictionary to store segment label names
# segment_label_names = {}
# for value in unique_segment_labels:
#     if value in segment_mapping:
#         segment_label_names[value] = segment_mapping[value]

# # Print the segment label names
# print("Segment Label Names:", segment_label_names)


# Define the valid segmentation values (0, 1, 2, 3)
valid_segmentation_values = [0, 1, 2, 3]

# Replace values not in valid_segmentation_values with 0
data[np.logical_not(np.isin(data, valid_segmentation_values))] = 0

# Calculate voxel counts for each segmentation value
unique_values, counts = np.unique(data, return_counts=True)

# Create a dictionary to store counts based on segment label name
segment_counts = {}
for value, count in zip(unique_values, counts):
    segment_counts[str(value)] = count

# Sort the segment_counts dictionary by counts in descending order
sorted_counts = sorted(segment_counts.items(), key=lambda x: x[1], reverse=True)

# Determine the highest, second highest, and lowest counts
highest_count = sorted_counts[0][1]
second_highest_count = sorted_counts[1][1]
lowest_count = sorted_counts[-1][1]

# Set the segmentation volume with the highest count to 0
data[data == int(sorted_counts[0][0])] = 0

# Set the segmentation volume with the second highest count to 'V'
data[data == int(sorted_counts[1][0])] = 1  # Assign 1 for 'V' label

# Set the segmentation volume with the lowest count (excluding 0) to 'A'
data[data == int(sorted_counts[-1][0])] = 2  # Assign 2 for 'A' label

# Set all other segmentation volume values to 0
data[np.logical_not(np.isin(data, [0, 1, 2]))] = 0

# Save the modified data as a new .nrrd file
output_file_path = 'C:/Users/Adam/Desktop/Programs/code_testing/python_file_rename_copy/Case-22-0.5_A_80KV_Qr40d_3_53062428/MarkUps/88-Jensen/S-Segmentation-1-newTest4.nrrd'
nrrd.write(output_file_path, data, header)


OrderedDict([('type', 'unsigned char'), ('dimension', 3), ('space', 'left-posterior-superior'), ('sizes', array([684, 495, 679])), ('space directions', array([[0.38, 0.  , 0.  ],
       [0.  , 0.38, 0.  ],
       [0.  , 0.  , 0.38]])), ('kinds', ['domain', 'domain', 'domain']), ('encoding', 'gzip'), ('space origin', array([-126.6, -256.3, -563.4])), ('Segment0_Color', '0.847059 0.396078 0.309804'), ('Segment0_ColorAutoGenerated', '1'), ('Segment0_Extent', '0 683 5 480 47 678'), ('Segment0_ID', 'Segment_1'), ('Segment0_LabelValue', '1'), ('Segment0_Layer', '0'), ('Segment0_Name', 'A Seed'), ('Segment0_NameAutoGenerated', '0'), ('Segment0_Tags', 'Segmentation.Status:inprogress|TerminologyEntry:Segmentation category and type - 3D Slicer General Anatomy list~SCT^85756007^Tissue~SCT^51114001^Artery~^^~Anatomic codes - DICOM master list~^^~^^|'), ('Segment1_Color', '0 0.592157 0.807843'), ('Segment1_ColorAutoGenerated', '1'), ('Segment1_Extent', '0 683 5 480 47 678'), ('Segment1_ID', 'Segmen

In [5]:
import numpy as np
import nrrd

# Load the .nrrd file
file_path = 'C:/Users/Adam/Desktop/Programs/code_testing/python_file_rename_copy/Case-22-0.5_A_80KV_Qr40d_3_53062428/MarkUps/88-Jensen/S-Segmentation-1.nrrd'
data, header = nrrd.read(file_path)

# Define the valid segmentation values (0, 1, 2, 3)
valid_segmentation_values = [0, 1, 2, 3]

# Replace values not in valid_segmentation_values with 0
data[np.logical_not(np.isin(data, valid_segmentation_values))] = 0

# Calculate voxel counts for each segmentation value
unique_values, counts = np.unique(data, return_counts=True)

# Create a dictionary to store counts based on segment label name
segment_counts = {}
for value, count in zip(unique_values, counts):
    segment_counts[str(value)] = count

# Sort segment_counts in descending order of counts
sorted_segment_counts = dict(sorted(segment_counts.items(), key=lambda item: item[1], reverse=True))

# Determine the highest, second highest, and lowest non-zero counts
highest_count = None
second_highest_count = None
lowest_nonzero_count = None
for value, count in sorted_segment_counts.items():
    if count > 0:
        if highest_count is None:
            highest_count = count
            data[data == int(value)] = 0  # Set the volume with the highest count to 0
        elif second_highest_count is None:
            second_highest_count = count
            data[data == int(value)] = 0  # Set the second highest count volume to 0
            data[data == 0] = int(value)  # Rename the second highest count volume to 'V'
            segment_label = f'Segment{int(value)}_Name'
            header[segment_label] = 'V'
        else:
            lowest_nonzero_count = count
            data[data == int(value)] = 0  # Set the volume with the lowest count to 0
            if int(value) != 0:
                segment_label = f'Segment{int(value)}_Name'
                header[segment_label] = 'A'

# Remove segment labels from header
for value in valid_segmentation_values:
    segment_label = f'Segment{value}_Name'
    if segment_label in header:
        del header[segment_label]

# Save the modified data as a new .nrrd file
output_file_path = 'C:/Users/Adam/Desktop/Programs/code_testing/python_file_rename_copy/Case-22-0.5_A_80KV_Qr40d_3_53062428/MarkUps/88-Jensen/S-Segmentation-1-newTest6.nrrd'
nrrd.write(output_file_path, data, header)


In [17]:
import numpy as np
import nrrd

# Load the .nrrd file
file_path = 'C:/Users/Adam/Desktop/Programs/code_testing/python_file_rename_copy/Case-22-0.5_A_80KV_Qr40d_3_53062428/MarkUps/88-Jensen/S-Segmentation-1.nrrd'
data, header = nrrd.read(file_path)

# Define the valid segmentation values (0, 1, 2, 3)
valid_segmentation_values = [0, 1, 2, 3]

# Replace values not in valid_segmentation_values with 0
data[np.logical_not(np.isin(data, valid_segmentation_values))] = 0

# Calculate voxel counts for each segmentation value
unique_values, counts = np.unique(data, return_counts=True)

# Create a dictionary to store counts based on segment label value
segment_counts = {}
for value, count in zip(unique_values, counts):
    if value != 0:
        segment_counts[value] = count

# Sort segment_counts in descending order of counts
sorted_segment_counts = dict(sorted(segment_counts.items(), key=lambda item: item[1], reverse=True))

# Determine the highest, second highest, and third highest counts
highest_value = None
second_highest_value = None
lowest_nonzero_value = None
for value in sorted_segment_counts.keys():
    if highest_value is None:
        highest_value = value
    elif second_highest_value is None:
        second_highest_value = value
    elif lowest_nonzero_value is None:
        lowest_nonzero_value = value
        break

# Rename segments based on counts and update header
for value in sorted_segment_counts.keys():
    if value == highest_value:
        data[data == value] = 0  # Set the segment with the highest count to 0
        header.pop(f'Segment{value}_Name', None)  # Remove the segment label from header if exists
    elif value == second_highest_value:
        data[data == value] = 0  # Set the segment with the second highest count to 0
        header['Segment1_Name'] = 'V'  # Rename the header key to 'V'
    elif value == lowest_nonzero_value:
        data[data == value] = 0  # Set the segment with the lowest count to 0
        header['Segment2_Name'] = 'A'  # Rename the header key to 'A'
    else:
        data[data == value] = 0  # Set other segments to 0
        header.pop(f'Segment{value}_Name', None)  # Remove the segment label from header if exists

# Set all remaining non-zero segments to 0
data[data != 0] = 0

# Save the modified data and header as a new .nrrd file
output_file_path = 'C:/Users/Adam/Desktop/Programs/code_testing/python_file_rename_copy/Case-22-0.5_A_80KV_Qr40d_3_53062428/MarkUps/88-Jensen/S-Segmentation-1-newTest7.nrrd'
nrrd.write(output_file_path, data, header)





In [18]:
import numpy as np
import nrrd

# Load the .nrrd file
file_path = 'C:/Users/Adam/Desktop/Programs/code_testing/python_file_rename_copy/Case-22-0.5_A_80KV_Qr40d_3_53062428/MarkUps/88-Jensen/S-Segmentation-1.nrrd'
data, header = nrrd.read(file_path)

# Define the valid segmentation values (0, 1, 2, 3)
valid_segmentation_values = [0, 1, 2, 3]

# Replace values not in valid_segmentation_values with 0
data[np.logical_not(np.isin(data, valid_segmentation_values))] = 0

# Calculate voxel counts for each segmentation value
unique_values, counts = np.unique(data, return_counts=True)

# Create a dictionary to store counts based on segment label value
segment_counts = {}
for value, count in zip(unique_values, counts):
    if value != 0:
        segment_counts[value] = count

# Sort segment_counts in descending order of counts
sorted_segment_counts = dict(sorted(segment_counts.items(), key=lambda item: item[1], reverse=True))

# Determine the highest, second highest, and third highest counts
highest_value = None
second_highest_value = None
lowest_nonzero_value = None
for value in sorted_segment_counts.keys():
    if highest_value is None:
        highest_value = value
    elif second_highest_value is None:
        second_highest_value = value
    elif lowest_nonzero_value is None:
        lowest_nonzero_value = value
        break

# Rename segments based on counts and update header
for value in sorted_segment_counts.keys():
    if value == highest_value:
        data[data == value] = 0  # Set the segment with the highest count to 0
        header.pop(f'Segment{value}_Name', None)  # Remove the segment label from header if exists
    elif value == second_highest_value:
        data[data == value] = 0  # Set the segment with the second highest count to 0
        header['Segment1_Name'] = 'V'  # Rename the header key to 'V'
    elif value == lowest_nonzero_value:
        data[data == value] = 0  # Set the segment with the lowest count to 0
        header['Segment2_Name'] = 'A'  # Rename the header key to 'A'
    else:
        data[data == value] = 0  # Set other segments to 0
        header.pop(f'Segment{value}_Name', None)  # Remove the segment label from header if exists

# Set all remaining non-zero segments to 0
data[data != 0] = 0

# Save the modified data and header as a new .nrrd file
output_file_path = 'C:/Users/Adam/Desktop/Programs/code_testing/python_file_rename_copy/Case-22-0.5_A_80KV_Qr40d_3_53062428/MarkUps/88-Jensen/S-Segmentation-1-newTest7.nrrd'
nrrd.write(output_file_path, data, header)


In [23]:
import numpy as np
import nrrd

# Load the .nrrd file
file_path = 'C:/Users/Adam/Desktop/Programs/code_testing/python_file_rename_copy/Case-22-0.5_A_80KV_Qr40d_3_53062428/MarkUps/88-Jensen/S-Segmentation-1.nrrd'
data, header = nrrd.read(file_path)


for key, value in header.items():
    print(f"Key: {key}")
    print(f"Value: {value}")
    print("------")


# Define the valid segmentation values (0, 1, 2, 3)
valid_segmentation_values = [0, 1, 2, 3]

# Replace values not in valid_segmentation_values with 0
data[np.logical_not(np.isin(data, valid_segmentation_values))] = 0

# Calculate voxel counts for each segmentation value
unique_values, counts = np.unique(data, return_counts=True)

# Create a dictionary to store counts based on segment label value
segment_counts = {}
for value, count in zip(unique_values, counts):
    if value != 0:
        segment_counts[value] = count

# Sort segment_counts in descending order of counts
sorted_segment_counts = dict(sorted(segment_counts.items(), key=lambda item: item[1], reverse=True))

# Determine the highest, second highest, and third highest counts
highest_value = None
second_highest_value = None
third_highest_value = None
for value in sorted_segment_counts.keys():
    if highest_value is None:
        highest_value = value
    elif second_highest_value is None:
        second_highest_value = value
    elif third_highest_value is None:
        third_highest_value = value
        break

# Rename segments based on counts and update header
for value in sorted_segment_counts.keys():
    if value == highest_value:
        data[data == value] = 0  # Set the segment with the highest count to 0
        header.pop(f'Segment{value}_Name', None)  # Remove the segment label from header if exists
    elif value == second_highest_value:
        data[data == value] = 2  # Set the segment with the second highest count to 2
        header['Segment2_Name'] = 'V'  # Rename the header key to 'V'
    elif value == third_highest_value:
        data[data == value] = 1  # Set the segment with the third highest count to 1
        header['Segment1_Name'] = 'A'  # Rename the header key to 'A'
    else:
        data[data == value] = 0  # Set other segments to 0
        header.pop(f'Segment{value}_Name', None)  # Remove the segment label from header if exists

# Check and modify segment names based on their values
if 'Segment1_Name' in header:
    if header['Segment0_Name'].lower() in ['a', 'artery', 'a seed']:
        header['Segment0_Name'] = 'A'
        
if 'Segment2_Name' in header:
    if header['Segment1_Name'].lower() in ['v', 'vein', 'v seed']:
        header['Segment1_Name'] = 'V'
        
if 'Segment3_Name' in header:
    if header['Segment2_Name'].lower() in ['m', 'misc', 'm seed']:
        header['Segment2_Name'] = 'M'
        del header['Segment2_Name']

# Set all remaining non-zero segments to 0
data[data != 0] = 0

# Save the modified data and header as a new .nrrd file
output_file_path = 'C:/Users/Adam/Desktop/Programs/code_testing/python_file_rename_copy/Case-22-0.5_A_80KV_Qr40d_3_53062428/MarkUps/88-Jensen/S-Segmentation-1-newTest8.nrrd'
nrrd.write(output_file_path, data, header)


Key: type
Value: unsigned char
------
Key: dimension
Value: 3
------
Key: space
Value: left-posterior-superior
------
Key: sizes
Value: [684 495 679]
------
Key: space directions
Value: [[0.38 0.   0.  ]
 [0.   0.38 0.  ]
 [0.   0.   0.38]]
------
Key: kinds
Value: ['domain', 'domain', 'domain']
------
Key: encoding
Value: gzip
------
Key: space origin
Value: [-126.6 -256.3 -563.4]
------
Key: Segment0_Color
Value: 0.847059 0.396078 0.309804
------
Key: Segment0_ColorAutoGenerated
Value: 1
------
Key: Segment0_Extent
Value: 0 683 5 480 47 678
------
Key: Segment0_ID
Value: Segment_1
------
Key: Segment0_LabelValue
Value: 1
------
Key: Segment0_Layer
Value: 0
------
Key: Segment0_Name
Value: A Seed
------
Key: Segment0_NameAutoGenerated
Value: 0
------
Key: Segment0_Tags
Value: Segmentation.Status:inprogress|TerminologyEntry:Segmentation category and type - 3D Slicer General Anatomy list~SCT^85756007^Tissue~SCT^51114001^Artery~^^~Anatomic codes - DICOM master list~^^~^^|
------
Key: Seg

In [ ]:
# read Input, convert to uchar, list all unique values in dataset(image), find largest (Misc), medium(Vein), smallest(Artery) - print to verify sizes



# A=2
# V=3
# M:SHouldBedeleted=1
# BackGroundEmptySpace=4

# OutputLabelMap = zeros_like(input)
# OutputVolume [InputVolume == 2] = 1
# OutputVolume [InputVolume == 3] = 2


In [1]:
# This code attempts to combine both setting segment labels to 0 if not 0, 1 or 2, and remove the segment label names from the list of
    # all segment labels in the segmentation file [GETTING ERROR 'AttributeError: module 'slicer' has no attribute 'util'']

import os
import slicer
import nrrd
import numpy as np

# Replace with the path to your segmentation file
input_path = 'C:/Users/Adam/Desktop/Programs/code_testing/python_file_rename_copy/Case-22-0.5_A_80KV_Qr40d_3_53062428/MarkUps/88-Jensen/S-Segmentation-1.nrrd'

# Replace with the desired output path for the modified segmentation
output_path = 'C:/Users/Adam/Desktop/Programs/code_testing/python_file_rename_copy/Case-22-0.5_A_80KV_Qr40d_3_53062428/MarkUps/88-Jensen/S-Segmentation-1-newTest1'

# List of segment labels to keep
keep_labels = ['A', 'Artery']

# List of segment values to keep
keep_values = [0, 1, 2]

# Load the segmentation node from the file
segmentation_node = slicer.util.loadSegmentation(input_path)

# Get the segmentation node's segmentation object
segmentation = segmentation_node.GetSegmentation()

# Iterate through existing segments and remove those not in the keep_labels list
segments_to_remove = [segment for segment in segmentation.GetSegments() if segment.GetName() not in keep_labels]
for segment in segments_to_remove:
    segmentation.RemoveSegment(segment)

# Save the modified segmentation node (optional)
slicer.util.saveNode(segmentation_node, output_path)

# Clean up by closing the segmentation node
slicer.mrmlScene.RemoveNode(segmentation_node)

# Read the modified segmentation data using pynrrd
data, header = nrrd.read(output_path)

# Update the segmentation data to keep only specific values
data = np.where(np.isin(data, keep_values), data, 0)

# Save the modified segmentation data using pynrrd
nrrd.write(output_path, data, header)


AttributeError: module 'slicer' has no attribute 'util'